// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Me605EcBuj_qWDLbE66d3fXgApwbj3s',
    appId: '1:1056489916400:web:0832a5efe88c16cbe1ff35',
    messagingSenderId: '1056489916400',
    projectId: 'fox-link-app',
    authDomain: 'fox-link-app.firebaseapp.com',
    storageBucket: 'fox-link-app.firebasestorage.app',
    measurementId: 'G-0KMTGS1WG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKl7IEEWqPqx1SfefYHThERqqRot1VC0M',
    appId: '1:1056489916400:android:d8eb5b59bd8491a7e1ff35',
    messagingSenderId: '1056489916400',
    projectId: 'fox-link-app',
    storageBucket: 'fox-link-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfpgtaZEIwx9CNSsUQ2I_cMxiiVgMb6bQ',
    appId: '1:1056489916400:ios:82774bc95cd033dae1ff35',
    messagingSenderId: '1056489916400',
    projectId: 'fox-link-app',
    storageBucket: 'fox-link-app.firebasestorage.app',
    iosBundleId: 'com.example.foxlinkSolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Me605EcBuj_qWDLbE66d3fXgApwbj3s',
    appId: '1:1056489916400:web:25510919af8bc187e1ff35',
    messagingSenderId: '1056489916400',
    projectId: 'fox-link-app',
    authDomain: 'fox-link-app.firebaseapp.com',
    storageBucket: 'fox-link-app.firebasestorage.app',
    measurementId: 'G-JXKKJGXQTY',
  );
}
